version: "3.8"

services:
  app:
    container_name: app
    image: node:alpine
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    command: sh -c "npm install && npm run start"
    depends_on:
      - server

  server:
    container_name: server
    image: maven:3.9.9-eclipse-temurin-23
    working_dir: /usr/src/server
    volumes:
      - ./server:/usr/src/server
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/desafio1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: desafio1
    command: mvn spring-boot:run
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: desafio1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: desafio1

volumes:
  pgdata:
